# Generated by Django 6.1 on 2026-08-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('reduction_pourcentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reduction_montant', models.PositiveIntegerField(blank=True, help_text='FCFA — laisser vide si réduction en %', null=True)),
                ('montant_minimum', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('expire_le', models.DateField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, help_text='Laisser vide pour un coupon valable sur tout le site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categorie')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilise_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.commande')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='promotions.coupon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons_utilises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'utilisateur')},
            },
        ),
    ]
