# Generated by Django 6.1 on 2026-08-15 12:05

import commandes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=commandes.models.generer_reference, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('commande_confirmee', 'Commande confirmée'), ('paiement_confirme', 'Paiement confirmé'), ('preparation', 'Préparation'), ('expedition', 'Expédition'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='commande_confirmee', max_length=30)),
                ('adresse_texte', models.CharField(max_length=255)),
                ('mode_livraison', models.CharField(choices=[('standard', 'Livraison standard'), ('express', 'Livraison express'), ('retrait', 'Retrait en magasin')], default='standard', max_length=20)),
                ('frais_livraison', models.PositiveIntegerField(default=0)),
                ('sous_total', models.PositiveIntegerField()),
                ('reduction', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('commande_confirmee', 'Commande confirmée'), ('paiement_confirme', 'Paiement confirmé'), ('preparation', 'Préparation'), ('expedition', 'Expédition'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.PositiveIntegerField(help_text='Prix figé au moment de la commande')),
            ],
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('carte', 'Carte bancaire'), ('livraison', 'Paiement à la livraison')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('montant', models.PositiveIntegerField()),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100, unique=True)),
                ('prix', models.PositiveIntegerField()),
                ('delai', models.CharField(help_text='ex: 24h, 24-48h, 3-5 jours', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['ordre', 'commune'],
            },
        ),
    ]
