# Generated by Django 6.1 on 2026-08-15 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(help_text="Nom d'icône lucide-react, ex: baby", max_length=50)),
                ('couleur', models.CharField(choices=[('sauge', 'Sauge'), ('corail', 'Corail'), ('lavande', 'Lavande'), ('ciel', 'Ciel')], default='sauge', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.PositiveIntegerField(help_text='FCFA, sans décimales')),
                ('ancien_prix', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('seuil_stock_faible', models.PositiveIntegerField(default=5)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Référence (SKU)')),
                ('contenance', models.CharField(blank=True, max_length=50)),
                ('poids', models.CharField(blank=True, max_length=50)),
                ('age_recommande', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('composition', models.TextField(blank=True)),
                ('mode_utilisation', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('lot', models.CharField(blank=True, max_length=50)),
                ('date_fabrication', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('est_nouveaute', models.BooleanField(default=False, verbose_name='Nouveauté')),
                ('est_bestseller', models.BooleanField(default=False, verbose_name='Best-seller')),
                ('actif', models.BooleanField(default=True, verbose_name='Publié')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.categorie')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.marque')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='catalogue.categorie')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('categorie', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalogue.souscategorie'),
        ),
    ]
